### ISSUE TITLE
ValueError("Please specify target_modules in peft_config")

### ISSUE THREAD

**Issue by NarenZen** [h2oai/h2o-llmstudio#117]
I'm finetuning mpt-instruct model.
huggng face: mosaicml/mpt-7b-instruct

### 🐛 Bug

But i got an error:
`ValueError("Please specify `target_modules` in `peft_config`") `

here is the full traceback:
```
Traceback (most recent call last):
  File "/Data1/h2o-llmstudio/train_wave.py", line 106, in <module>
    run(cfg=cfg)
  File "/Data1/h2o-llmstudio/train.py", line 510, in run
    model = cfg.architecture.model_class(cfg)
  File "/Data1/h2o-llmstudio/llm_studio/src/models/text_causal_language_modeling_model.py", line 114, in __init__
    self.backbone = get_peft_model(self.backbone, lora_config)
  File "/home/naren/.local/share/virtualenvs/h2o-llmstudio-IuguWLXF/lib/python3.10/site-packages/peft/mapping.py", line 120, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config)
  File "/home/naren/.local/share/virtualenvs/h2o-llmstudio-IuguWLXF/lib/python3.10/site-packages/peft/peft_model.py", line 662, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/home/naren/.local/share/virtualenvs/h2o-llmstudio-IuguWLXF/lib/python3.10/site-packages/peft/peft_model.py", line 99, in __init__
    self.base_model = PEFT_TYPE_TO_MODEL_MAPPING[peft_config.peft_type](
  File "/home/naren/.local/share/virtualenvs/h2o-llmstudio-IuguWLXF/lib/python3.10/site-packages/peft/tuners/lora.py", line 132, in __init__
    self.add_adapter(adapter_name, self.peft_config[adapter_name])
  File "/home/naren/.local/share/virtualenvs/h2o-llmstudio-IuguWLXF/lib/python3.10/site-packages/peft/tuners/lora.py", line 137, in add_adapter
    config = self._prepare_lora_config(config, model_config)
  File "/home/naren/.local/share/virtualenvs/h2o-llmstudio-IuguWLXF/lib/python3.10/site-packages/peft/tuners/lora.py", line 293, in _prepare_lora_config
    raise ValueError("Please specify `target_modules` in `peft_config`")
ValueError: Please specify `target_modules` in `peft_config`

```
### To Reproduce
just gave input to LLM Backbone as mosaicml/mpt-7b-instruct
remaining all setting were default

**Comment by pascal-pfeiffer** [comment]
MPT has no default target modules set for LoRA training in peft (yet). 

As the error suggests, you will need to specify `target_modules`. In H2O LLM Studio, this is the `Lora Target Modules` parameter.
