### ISSUE TITLE
[BUG] Chat Window may fail to load model

### ISSUE THREAD

**Issue by maxjeblick** [h2oai/h2o-llmstudio#137]
### 🐛 Bug

In an experiment that was started from an existing experiment, the interactive chat window fails with 
`ValueError: Loading this model requires you to execute the modeling file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.`

In `config.yaml`, trust remote code is enabled, so unsure where this error originates. The error does not appear when I open the chat tab of the original model.

### To Reproduce
- train a falcon model
- start from an existing experiment and use the previous experiments weights.

```
q.app

script_sources: ['/_f/5d8f7bd8-dd93-42bf-b56b-a166fc547588/tmppveubfi4.min.js']
initialized: True
wave_utils_stack_trace_str: ### stacktrace
Traceback (most recent call last):

  File "/data/maxjeblick/PyCharmProjects/h2o-llmstudio/./app_utils/handlers.py", line 314, in handle
    await experiment_display(q)

  File "/data/maxjeblick/PyCharmProjects/h2o-llmstudio/./app_utils/sections/experiment.py", line 949, in experiment_display
    await chat_tab(q)

  File "/data/maxjeblick/PyCharmProjects/h2o-llmstudio/./app_utils/sections/experiment.py", line 1167, in chat_tab
    cfg, model, tokenizer = load_cfg_model_tokenizer(

  File "/data/maxjeblick/PyCharmProjects/h2o-llmstudio/./app_utils/sections/experiment.py", line 1896, in load_cfg_model_tokenizer
    model = cfg.architecture.model_class(cfg)

  File "/data/maxjeblick/PyCharmProjects/h2o-llmstudio/./llm_studio/src/models/text_causal_language_modeling_model.py", line 97, in __init__
    self.backbone = create_nlp_backbone(

  File "/data/maxjeblick/PyCharmProjects/h2o-llmstudio/./llm_studio/src/utils/modeling_utils.py", line 499, in create_nlp_backbone
    backbone = model_class.from_config(config, **kwargs)

  File "/home/maxjeblick/.local/share/virtualenvs/h2o-llmstudio-07dpqO7E/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 395, in from_config
    raise ValueError(

ValueError: Loading this model requires you to execute the modeling file in that repo on your local machine. Make sure you have read the code there to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.


```

**Comment by maxjeblick** [comment]
Fixed already by https://github.com/h2oai/h2o-llmstudio/pull/132, sorry overlooked it.
