### ISSUE TITLE
[BUG] Check disk space of the output directory

### ISSUE THREAD

**Issue by Glavin001** [h2oai/h2o-llmstudio#214]
### 🐛 Bug

When running the disk space calculation was for the wrong directory. Therefore, it said there was space (only 2.5% used) and started running when really the `output` directory was already full.
Unfortunately I neglected to notice it was showing % of the small volume not the larger `output` data volume which was already consumed by a previous run ( #213 ).

| H2O LLM Studio | Runpod |
| --- | --- |
| <img width="258" alt="image" src="https://github.com/h2oai/h2o-llmstudio/assets/1885333/26d07ba7-eb90-4cd9-8ab1-f285578e9280"> |  <img width="649" alt="image" src="https://github.com/h2oai/h2o-llmstudio/assets/1885333/790328b1-0556-49a1-b38b-61f7f9224dd8"> |

Error received when saving checkpoint:

```
2023-07-01 16:41:05,669 - ERROR: Exception occurred during H2O LLM Studio run:
Traceback (most recent call last):
File "/root/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.10/site-packages/torch/serialization.py", line 441, in save
_save(obj, opened_zipfile, pickle_module, pickle_protocol)
File "/root/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.10/site-packages/torch/serialization.py", line 668, in _save
zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at inline_container.cc:471] . PytorchStreamWriter failed writing file data/228: file write failed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/workspace/train_wave.py", line 106, in
run(cfg=cfg)
File "/workspace/train.py", line 697, in run
save_checkpoint(model=model, path=checkpoint_path, cfg=cfg)
File "/workspace/llm_studio/src/utils/modeling_utils.py", line 59, in save_checkpoint
torch.save(checkpoint, os.path.join(path, "checkpoint.pth"))
File "/root/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.10/site-packages/torch/serialization.py", line 440, in save
with _open_zipfile_writer(f) as opened_zipfile:
File "/root/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.10/site-packages/torch/serialization.py", line 291, in __exit__
self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:337] . unexpected pos 13452142400 vs 13452142296
```

### To Reproduce

Coming soon.

**Comment by Glavin001** [comment]
I was using a version of LLM Studio which was 5 days old. I see the `check_disk_space` was added 4 days ago: https://github.com/h2oai/h2o-llmstudio/pull/194

Going to try to update (need #217 first) and will report if I see it again. If not consider this closed.
