### ISSUE TITLE
[BUG] CUDA Error when using 'Add Prompt Answer Tokens' 

### ISSUE THREAD

**Issue by luizlf** [h2oai/h2o-llmstudio#227]
### 🐛 Bug

Got the error below for an experiment with backbone `tiiuae/falcon-7b-instruct` and option 'Add Prompt Answer Tokens' set to True. The error happens with 'Force Embedding Gradients' set to either True or False.

`2023-07-03 11:40:25,696 - INFO: Number of observations in train dataset: 44778
2023-07-03 11:40:25,696 - INFO: Number of observations in validation dataset: 453
2023-07-03 11:40:26,399 - INFO: dtype: torch.float16
2023-07-03 11:40:43,594 - INFO: Training Epoch: 1 / 1
2023-07-03 11:40:43,595 - INFO: train loss: 0%| | 0/14926 [00:00
2023-07-03 11:40:44,483 - INFO: Stop token ids: [tensor([65025]), tensor([65024])]
2023-07-03 11:40:44,693 - ERROR: Exception occurred during H2O LLM Studio run:
Traceback (most recent call last):
File "/home/fsuser/projects/h2o-llmstudio/train_wave.py", line 106, in
run(cfg=cfg)
File "/home/fsuser/projects/h2o-llmstudio/train.py", line 570, in run
val_data, val_loss, val_metric, last_batch = run_train(
File "/home/fsuser/projects/h2o-llmstudio/train.py", line 271, in run_train
output_dict = model.forward(batch)
File "/home/fsuser/projects/h2o-llmstudio/llm_studio/src/models/text_causal_language_modeling_model.py", line 193, in forward
output = self.backbone(
File "/home/fsuser/.local/share/virtualenvs/h2o-llmstudio-XOsEFuK8/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/home/fsuser/.local/share/virtualenvs/h2o-llmstudio-XOsEFuK8/lib/python3.10/site-packages/peft/peft_model.py", line 678, in forward
return self.base_model(
File "/home/fsuser/.local/share/virtualenvs/h2o-llmstudio-XOsEFuK8/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/home/fsuser/.cache/huggingface/modules/transformers_modules/tiiuae/falcon-7b-instruct/c7f670a03d987254220f343c6b026ea0c5147185/modelling_RW.py", line 753, in forward
transformer_outputs = self.transformer(
File "/home/fsuser/.local/share/virtualenvs/h2o-llmstudio-XOsEFuK8/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/home/fsuser/.cache/huggingface/modules/transformers_modules/tiiuae/falcon-7b-instruct/c7f670a03d987254220f343c6b026ea0c5147185/modelling_RW.py", line 648, in forward
outputs = block(
File "/home/fsuser/.local/share/virtualenvs/h2o-llmstudio-XOsEFuK8/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/home/fsuser/.cache/huggingface/modules/transformers_modules/tiiuae/falcon-7b-instruct/c7f670a03d987254220f343c6b026ea0c5147185/modelling_RW.py", line 385, in forward
attn_outputs = self.self_attention(
File "/home/fsuser/.local/share/virtualenvs/h2o-llmstudio-XOsEFuK8/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/home/fsuser/.cache/huggingface/modules/transformers_modules/tiiuae/falcon-7b-instruct/c7f670a03d987254220f343c6b026ea0c5147185/modelling_RW.py", line 242, in forward
fused_qkv = self.query_key_value(hidden_states) # [batch_size, seq_length, 3 x hidden_size]
File "/home/fsuser/.local/share/virtualenvs/h2o-llmstudio-XOsEFuK8/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/home/fsuser/.local/share/virtualenvs/h2o-llmstudio-XOsEFuK8/lib/python3.10/site-packages/peft/tuners/lora.py", line 493, in forward
result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)``

**Comment by psinger** [comment]
Thanks for reporting - will take a look.

**Comment by psinger** [comment]
Okay, seems to happen with falcon on any dtype, will try to see if/how to fix.
