### ISSUE TITLE
[BUG] llmstudio cannot read dataset

### ISSUE THREAD

**Issue by whatvn** [h2oai/h2o-llmstudio#259]
### 🐛 Bug
1. Create new experiment  using default dataset
I set up and run llm studio, create a new experiment using default oasst dataset. 
When start training, I got error: 
```
Traceback (most recent call last):
  File "/mnt/share/llm-experimental-2023/sources/h2o-llmstudio/train_wave.py", line 106, in <module>
    run(cfg=cfg)
  File "/mnt/share/llm-experimental-2023/sources/h2o-llmstudio/train.py", line 550, in run
    train_df, val_df = get_data(cfg)
  File "/mnt/share/llm-experimental-2023/sources/h2o-llmstudio/llm_studio/src/utils/data_utils.py", line 198, in get_data
    df = read_dataframe_drop_missing_labels(cfg.dataset.train_dataframe, cfg)
  File "/mnt/share/llm-experimental-2023/sources/h2o-llmstudio/llm_studio/src/utils/data_utils.py", line 138, in read_dataframe_drop_missing_labels
    df = read_dataframe(
  File "/mnt/share/llm-experimental-2023/sources/h2o-llmstudio/llm_studio/src/utils/data_utils.py", line 75, in read_dataframe
    df[fill_columns] = df[fill_columns].fillna(fill_value)
  File "/mnt/share/llm-experimental-2023/sources/h2o-llmstudio/lib/python3.10/site-packages/pandas/core/frame.py", line 3813, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/mnt/share/llm-experimental-2023/sources/h2o-llmstudio/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/mnt/share/llm-experimental-2023/sources/h2o-llmstudio/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6130, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['instruction,output,id,parent_id'], dtype='object')] are in the [columns]"
```

2. Using my dataset 
I create a new dataset in csv with format: 

```
instruction|output 
some question | answer 
......

```

When upload dataset to studio, it shows there's error but I don't know what error it's. Do we have document on how to produce valid dataset?

**Comment by psinger** [comment]
Hi @whatvn 

For 1):

Could you please exactly elaborate how you are trying to run this. 
The default dataset and config will run if you set up everything correctly. There might be another issue with the install potentially. 

For 2):

This does not look like valid CSV, `|` is not the default delimiter.
I suggest to try loading the CSV in pandas with `pd.read_csv("file.csv")` outside in a notebook to check if it can be loaded correctly.

**Comment by whatvn** [comment]
@psinger 
1) I install follow installation guide, and run studio using following command, I didn't change any configuration
```
H2O_WAVE_MAX_REQUEST_SIZE=25MB H2O_WAVE_NO_LOG=false  H2O_WAVE_LISTEN="0.0.0.0:8008" H2O_WAVE_ADDRESS="http://127.0.0.1:8008" wave run app
```
2) Even is use same format as default oasst dataset, I still get this error. The only difference is my dataset is unicode encoding (Vietnamese), is utf8 data a problem with training process?

**Comment by psinger** [comment]
Please run it with the pipenv, so first install via `make setup` and then run `make wave` as written in the README. 

Can you share a sample of your dataset? Otherwise it is very hard to debug. Feel free to send it to me privately.

**Comment by whatvn** [comment]
[train.csv](https://github.com/h2oai/h2o-llmstudio/files/11997083/train.csv)
@psinger thank, I attach minimum dataset here. Will check "make wave" status and get back later

**Comment by psinger** [comment]
@whatvn your csv is broken - please fix it and try again

`df = pd.read_csv("train.csv")`
is also breaking

**Comment by whatvn** [comment]
@psinger is there a guide to create standard dataset, or can you please provide a way to fix above csv file? Thank!

**Comment by psinger** [comment]
Here are the docs for generating the data:
https://docs.h2o.ai/h2o-llmstudio/guide/datasets/data-connectors-format

Please re-open this issue if you still encounter problems.
