### ISSUE TITLE
[BUG] INT8 Push to HF and loading weights

### ISSUE THREAD

**Issue by psinger** [h2oai/h2o-llmstudio#30]
### 🐛 Bug

When training a model with INT8 and LORA it does not work pushing it to HF:

```
2023-04-23 08:33:14,581 - ERROR: Unknown exception                                                                                                                 
Traceback (most recent call last):                                                                                                                                 
  File "/home/philipp/llm_studio/./app_utils/handlers.py", line 301, in handle                                                                                     
    await experiment_push_to_huggingface_dialog(q)                                                                                                                 
  File "/home/philipp/llm_studio/./app_utils/sections/experiment.py", line 1544, in experiment_push_to_huggingface_dialog                                          
    model.backbone = model.backbone.merge_and_unload()                                                                                                             
  File "/home/philipp/.local/share/virtualenvs/llm_studio-BMnV59HB/lib/python3.8/site-packages/peft/tuners/lora.py", line 309, in merge_and_unload                 
    raise ValueError("Cannot merge LORA layers when the model is loaded in 8-bit mode")                                                                            
ValueError: Cannot merge LORA layers when the model is loaded in 8-bit mode 
```
Additionally, when loading the weights for Chat window, we need to set `pretrained=True`.

There is also something else that is weird when loading the weights with missing keys, but the inference and score works fine:

```
2023-04-23 08:26:20,825 - WARNING: Only a part of the pretrained weights was loaded. Some layers can't be initialized with pretrained weights: Error(s) in loading
state_dict for Model:
        Missing key(s) in state_dict: "backbone.base_model.model.gpt_neox.layers.0.attention.query_key_value.weight", "backbone.base_model.model.gpt_neox.layers.0.
attention.dense.weight", "backbone.base_model.model.gpt_neox.layers.0.mlp.dense_h_to_4h.weight", "backbone.base_model.model.gpt_neox.layers.0.mlp.dense_4h_to_h.wei
ght", "backbone.base_model.model.gpt_neox.layers.1.attention.query_key_value.weight", "backbone.base_model.model.gpt_neox.layers.1.attention.dense.weight", "backbo
ne.base_model.model.gpt_neox.layers.1.mlp.dense_h_to_4h.weight", "backbone.base_model.model.gpt_neox.layers.1.mlp.dense_4h_to_h.weight", "backbone.base_model.model
.gpt_neox.layers.2.attention.query_key_value.weight", "backbone.base_model.model.gpt_neox.layers.2.attention.dense.weight", "backbone.base_model.model.gpt_neox.lay
ers.2.mlp.dense_h_to_4h.weight", "backbone.base_model.model.gpt_neox.layers.2.mlp.dense_4h_to_h.weight", ....
```

**Comment by arnocandel** [comment]
See https://github.com/h2oai/h2ogpt/blob/main/export_hf_checkpoint.py

**Comment by psinger** [comment]
Also fix for
https://github.com/h2oai/h2o-llmstudio/pull/44
