### ISSUE TITLE
[BUG] not pushing to hugging face

### ISSUE THREAD

**Issue by Stealthwriter** [h2oai/h2o-llmstudio#324]
### 🐛 Bug

when the model finishes fine tuning and i push it to hugging face , i get this error: 
![image](https://github.com/h2oai/h2o-llmstudio/assets/126798556/1043daf4-bc80-4233-902d-dd0a583438b7)

**Comment by psinger** [comment]
Please click on Report and paste the information here.

**Comment by Stealthwriter** [comment]
2023-07-30 17:49:25,772 - INFO: Setting pretraining_tp of model config to 1.
2023-07-30 17:49:25,776 - INFO: Using float16 for backbone
trainable params: 8,388,608 || all params: 6,746,804,224 || trainable%: 0.12433454005023165
2023-07-30 17:49:31,359 - INFO: Weights loaded from: /workspace/h2o-llmstudio/output/user/sincere-gazelle.1.1.1.1/checkpoint.pth
2023-07-30 17:49:31,360 - INFO: Merging LORA layers with base model.
2023-07-30 17:49:39,027 - INFO: Enough space available for saving model weights.
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Token is valid.
Your token has been saved to /root/.cache/huggingface/token
Login successful
2023-07-30 17:49:39,422 - ERROR: Unknown exception
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/h2o-llmstudio-e95QNfnv/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/root/.local/share/virtualenvs/h2o-llmstudio-e95QNfnv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/models/stealthwriter/para/commit/main

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/h2o-llmstudio/./app_utils/handlers.py", line 306, in handle
    await experiment_push_to_huggingface_dialog(q)
  File "/workspace/h2o-llmstudio/./app_utils/sections/experiment.py", line 1709, in experiment_push_to_huggingface_dialog
    tokenizer.push_to_hub(repo_id=repo_id, private=True)
  File "/root/.local/share/virtualenvs/h2o-llmstudio-e95QNfnv/lib/python3.10/site-packages/transformers/utils/hub.py", line 816, in push_to_hub
    return self._upload_modified_files(
  File "/root/.local/share/virtualenvs/h2o-llmstudio-e95QNfnv/lib/python3.10/site-packages/transformers/utils/hub.py", line 729, in _upload_modified_files
    return create_commit(
  File "/root/.local/share/virtualenvs/h2o-llmstudio-e95QNfnv/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/.local/share/virtualenvs/h2o-llmstudio-e95QNfnv/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2548, in create_commit
    hf_raise_for_status(commit_resp, endpoint_name="commit")
  File "/root/.local/share/virtualenvs/h2o-llmstudio-e95QNfnv/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 301, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/models/stealthwriter/para/commit/main (Request ID: Root=1-64c6a2b3-1b7ff0212da1ee1d3da99d03)

Forbidden: pass `create_pr=1` as a query parameter to create a Pull Request
2023-07-30 17:49:39,423 - INFO: {'experiment/display/chat/settings', 'experiment/display/charts/train_loss', 'experiment/start/footer', 'experiment/list', 'home/disk_usage', 'home/experiments_stats', 'experiment/display/charts/validation_loss', 'experiment/display/summary/main_configs', 'experiment/display/summary/code', 'home/compute_stats', 'experiment/display/config', 'dataset/import', 'experiment/display/logs', 'experiment/display/summary/experiment', 'experiment/display/tab', 'wave_utils_error', 'settings/content', 'experiment/start', 'settings/footer', 'experiment/display/footer', 'experiment/display/charts/validation_Perplexity', 'dataset/import/footer', 'home/gpu_stats', 'experiment/display/charts/meta_lr', 'experiment/display/summary/score', 'init_app', 'experiment/display/chat', 'dataset/list', 'dataset/display/footer', 'experiment/display/summary/datasets'}

**Comment by Stealthwriter** [comment]
> Please click on Report and paste the information here.

any idea how to fix this?

**Comment by psinger** [comment]
You are using the correct write token from Huggingface?

Error says forbidden.

**Comment by psinger** [comment]
@Stealthwriter did you manage to solve this?

**Comment by Stealthwriter** [comment]
> @Stealthwriter did you manage to solve this?

Thanks it worked, I was copying the read token not the write.
