### ISSUE TITLE
[BUG] automatically adding that /r to the output train DataFrame does not contain the required column: output

### ISSUE THREAD

**Issue by sooraj007** [h2oai/h2o-llmstudio#346]
### 🐛 Bug

when i debug it prompt_column=('instruction',), answer_column='output\r' its automatically adding that /r to the output, i checked my csv column name its  output. and training time when we select it seems correct but the experiment time i tried to inspect ui in the dropdown when opening output it shows space after r
so please fix this issue

**Comment by psinger** [comment]
It seems like csv is malformed and has a space or some other special character in the column name, would be my assumption.

Please try to check your csv and then try again.

**Comment by sooraj007** [comment]
> It seems like csv is malformed and has a space or some other special character in the column name, would be my assumption.
> 
> Please try to check your csv and then try again.

No i checked many times also tun a python script to check that but none reported that issue. in dataset interface its correct but no in experiment if that csv got issues i should come in both places right
also i downloaded another statndard csv from here https://github.com/tomasonjo/blog-datasets but that also got the same issue. any way i fixed it by making change in experiment.py 
cfg.dataset.answer_column = cfg.dataset.answer_column.replace('\r', '')

**Comment by psinger** [comment]
On what system are you running this?
Could you please share a csv causing this?

**Comment by sooraj007** [comment]
[train_llm.csv](https://github.com/h2oai/h2o-llmstudio/files/12288717/train_llm.csv)
@psinger i forgot to say that i am trying to port this natively to windows. so this is the file i am using 
i want to run this like running in ubuntu in windows without docker or wsl and i am some what achieving that 

fixed some obstacles while porting but now looking into another issue, below is the current status if you can help in that process please let me know. so i can save much time in figuring out

2023-08-08 13:12:30,814 - INFO: Enough space available for saving model weights.
2023-08-08 13:12:30,937 - INFO: Training Epoch: 1 / 1
2023-08-08 13:12:30,937 - INFO: train loss:   0%|          | 0/99 [00:00<?, ?it/s]
2023-08-08 13:12:30,949 - ERROR: Exception occurred during H2O LLM Studio run:
Traceback (most recent call last):
  File "I:\h2o-llmstudio\train_wave.py", line 106, in <module>
    run(cfg=cfg)
  File "I:\h2o-llmstudio\train.py", line 671, in run
    val_loss, val_metric = run_train(
  File "I:\h2o-llmstudio\train.py", line 246, in run_train
    tr_it = iter(train_dataloader)
  File "C:\Users\surajn\.virtualenvs\h2o-llmstudio-YC26HP0r-python\lib\site-packages\torch\utils\data\dataloader.py", line 442, in __iter__
    return self._get_iterator()
  File "C:\Users\surajn\.virtualenvs\h2o-llmstudio-YC26HP0r-python\lib\site-packages\torch\utils\data\dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\surajn\.virtualenvs\h2o-llmstudio-YC26HP0r-python\lib\site-packages\torch\utils\data\dataloader.py", line 1043, in __init__
    w.start()
  File "C:\Users\surajn\anaconda3\envs\hstudio\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\surajn\anaconda3\envs\hstudio\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\surajn\anaconda3\envs\hstudio\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\surajn\anaconda3\envs\hstudio\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\surajn\anaconda3\envs\hstudio\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'ConfigNLPCausalLMDataset.__post_init__.<locals>.<lambda>'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 15) local_rank: 0 (pid: 38900) of binary: C:\Users\surajn\.virtualenvs\h2o-llmstudio-YC26HP0r-python\Scripts\python.exe
Traceback (most recent call last):
  File "C:\Users\surajn\anaconda3\envs\hstudio\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\surajn\anaconda3\envs\hstudio\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\surajn\.virtualenvs\h2o-llmstudio-YC26HP0r-python\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "C:\Users\surajn\.virtualenvs\h2o-llmstudio-YC26HP0r-python\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\surajn\.virtualenvs\h2o-llmstudio-YC26HP0r-python\lib\site-packages\torch\distributed\run.py", line 794, in main
    run(args)
  File "C:\Users\surajn\.virtualenvs\h2o-llmstudio-YC26HP0r-python\lib\site-packages\torch\distributed\run.py", line 785, in run
    elastic_launch(
  File "C:\Users\surajn\.virtualenvs\h2o-llmstudio-YC26HP0r-python\lib\site-packages\torch\distributed\launcher\api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "C:\Users\surajn\.virtualenvs\h2o-llmstudio-YC26HP0r-python\lib\site-packages\torch\distributed\launcher\api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train_wave.py FAILED

**Comment by psinger** [comment]
We are not supporting Windows, I am not sure it will be easily possible to port it. You will be running into several issues down the road, like this `\r` issue that is a peculiarity of Windows.
