### ISSUE TITLE
[BUG] - IndexError when printing the available disk space

### ISSUE THREAD

**Issue by jdurago-rebellion** [h2oai/h2o-llmstudio#352]
### 🐛 Bug
Below is the error I'm getting when starting up the  `gcr.io/vorvan/h2oai/h2o-llmstudio:v0.0.6` image

```
2023-08-08 18:11:32,652 - INFO: Initializing client True
2023-08-08 18:11:32,781 - INFO: {'wave_utils_error', 'settings/footer', 'init_app', 'settings/content'}
2023-08-08 18:11:32,840 - ERROR: Unknown exception
Traceback (most recent call last):
  File "/workspace/./app_utils/handlers.py", line 71, in handle
    await home(q)
  File "/workspace/./app_utils/sections/home.py", line 29, in home
    {get_size_str(hdd.total, sig_figs=1)}",
  File "/workspace/./llm_studio/src/utils/export_utils.py", line 156, in get_size_str
    ret_str += f" {names[act_i]}"
IndexError: list index out of range
```

This is running in kubernetes with a pod having 28GB mem and 16GB  GPU memory

**Comment by maxjeblick** [comment]
Thanks for reporting the error.

`get_size_str(hdd.total, sig_figs=1)` does indeed break if `hdd.total > 1024 ** 5 - 1` which would correspond to `1024.0 TB` of total disc space. I will create a PR to fix the function.

I'm also wondering how this large number would come up. Any ideas?
