### ISSUE TITLE
No clear error message if training without GPU

### ISSUE THREAD

**Issue by gpnath82** [h2oai/h2o-llmstudio#357]
I am just trying to create an experiment with oasst datasets 
LLM backbone selected openlm-research/open_llama_7b
All other settings is default.

And I get this error

ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`input_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
Killed

Full log below

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
CUDA SETUP: Loading binary /home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/torch/cuda/__init__.py:546: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
2023-08-09 11:49:17,520 - INFO: Global random seed: 635003
2023-08-09 11:49:17,521 - WARNING: No OpenAI API Key set. Setting metric to BLEU.
2023-08-09 11:49:17,521 - INFO: Preparing the data...
2023-08-09 11:49:17,521 - INFO: Setting up automatic validation split...
2023-08-09 11:49:17,705 - INFO: Preparing train and validation data
2023-08-09 11:49:17,705 - INFO: Loading train dataset...
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
Using pad_token, but it is not set yet.
Using cls_token, but it is not set yet.
Using sep_token, but it is not set yet.
2023-08-09 11:49:18,459 - INFO: Stop token ids: [tensor([  718, 31912, 18569,   451, 31912, 31901]), tensor([  718, 31912,   488, 14622, 31912, 31901]), tensor([  718, 31912, 15322, 31912, 31901])]
2023-08-09 11:49:18,650 - INFO: Sample prompt: <|prompt|>What would the assumed affect on computer graphics then?</s><|answer|>
2023-08-09 11:49:18,650 - INFO: Loading validation dataset...
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
Using pad_token, but it is not set yet.
Using cls_token, but it is not set yet.
Using sep_token, but it is not set yet.
2023-08-09 11:49:19,414 - INFO: Stop token ids: [tensor([  718, 31912, 18569,   451, 31912, 31901]), tensor([  718, 31912,   488, 14622, 31912, 31901]), tensor([  718, 31912, 15322, 31912, 31901])]
2023-08-09 11:49:19,419 - INFO: Sample prompt: <|prompt|>Write a joke about my life</s><|answer|>
2023-08-09 11:49:19,419 - INFO: Number of observations in train dataset: 25072
2023-08-09 11:49:19,419 - INFO: Number of observations in validation dataset: 254
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
Using pad_token, but it is not set yet.
Using cls_token, but it is not set yet.
Using sep_token, but it is not set yet.
2023-08-09 11:49:20,221 - ERROR: Exception occurred during H2O LLM Studio run:
Traceback (most recent call last):
  File "/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 731, in convert_to_tensors
    tensor = as_tensor(value)
  File "/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/torch/utils/_device.py", line 62, in __torch_function__
    return func(*args, **kwargs)
  File "/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jupyter/h2ostudio/train_wave.py", line 106, in <module>
    run(cfg=cfg)
  File "/home/jupyter/h2ostudio/train.py", line 594, in run
    model = cfg.architecture.model_class(cfg)
  File "/home/jupyter/h2ostudio/llm_studio/src/models/text_causal_language_modeling_model.py", line 141, in __init__
    self.backbone, self.backbone_config = create_nlp_backbone(
  File "/home/jupyter/h2ostudio/llm_studio/src/utils/modeling_utils.py", line 530, in create_nlp_backbone
    config = update_backbone_config(config, cfg)
  File "/home/jupyter/h2ostudio/llm_studio/src/utils/modeling_utils.py", line 478, in update_backbone_config
    tokenizer = get_tokenizer(cfg)
  File "/home/jupyter/h2ostudio/llm_studio/src/datasets/text_utils.py", line 111, in get_tokenizer
    tokenizer(stop_word, return_tensors="pt", add_special_tokens=False)[
  File "/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2577, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2683, in _call_one
    return self.encode_plus(
  File "/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2756, in encode_plus
    return self._encode_plus(
  File "/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 497, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 473, in _batch_encode_plus
    return BatchEncoding(sanitized_tokens, sanitized_encodings, tensor_type=return_tensors)
  File "/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 211, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/home/g30097220/.local/share/virtualenvs/h2ostudio-KXp7YeDl/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 747, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`input_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
Killed
make: *** [Makefile:86: llmstudio] Error 137

**Comment by maxjeblick** [comment]
Hi @gpnath82, the error message states  `RuntimeError: No CUDA GPUs are available` 
The error can also be reproduced on a GPU machine by setting
`CUDA_VISIBLE_DEVICES= make llmstudio`

**Comment by gpnath82** [comment]
@maxjeblick  hello Max I lost my GPU, can't we run this without GPU ?

on text_utils.py I have set padding=True but still no luck.

**Comment by maxjeblick** [comment]
Sorry to hear that you lost your GPU! 

While you cannot finetune without GPUs, you could use the CLI functionality to finetune (smaller) models on kaggle or colab:
https://www.kaggle.com/code/philippsinger/h2o-llm-studio-cli

**Comment by gpnath82** [comment]
@maxjeblick  Thank you Max for quick help. there is mad rush for GPU in google cloud in India. Not a single GPU is available in any of the zones. I have now ordered 2 L4 GPUs in Singapore.
