### ISSUE TITLE
[BUG] failing chat & hf push

### ISSUE THREAD

**Issue by fatihozturkh2o** [h2oai/h2o-llmstudio#46]
### 🐛 Bug

I realized that when I have Backbone Dtype selected as "int8", I'm not able to run Chat or push the model into HF with the following error thrown in the logs

Log:
```
Using cls_token, but it is not set yet.
Using sep_token, but it is not set yet.
2023-04-25 13:45:25,249 - INFO: dtype: torch.float16
2023-04-25 13:45:25,262 - ERROR: Unknown exception
Traceback (most recent call last):
  File "/home/fatih/h2o-llmstudio/./app_utils/handlers.py", line 308, in handle
    await experiment_display(q)
  File "/home/fatih/h2o-llmstudio/./app_utils/sections/experiment.py", line 1063, in experiment_display
    cfg, model, tokenizer = load_cfg_model_tokenizer(
  File "/home/fatih/h2o-llmstudio/./app_utils/sections/experiment.py", line 1600, in load_cfg_model_tokenizer
    model = cfg.architecture.model_class(cfg)
  File "/home/fatih/h2o-llmstudio/./llm_studio/src/models/text_causal_language_modeling_model.py", line 48, in __init__
    self.backbone = create_nlp_backbone(
  File "/home/fatih/h2o-llmstudio/./llm_studio/src/utils/modeling_utils.py", line 620, in create_nlp_backbone
    backbone = model_class.from_config(config, **kwargs)
  File "/home/fatih/h2o-llmstudio/venv/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 411, in from_config
    return model_class._from_config(config, **kwargs)
  File "/home/fatih/h2o-llmstudio/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1146, in _from_config
    model = cls(config, **kwargs)
TypeError: OPTForCausalLM.__init__() got an unexpected keyword argument 'device_map'
```

Based on my tests, the issue is about this backbone dtype setting. If I only change it back to float16, it all works. And if you also look at the logs, at the top, there is still some torch.float16 check? though it's from the int8 experiment.

to produce the issue, you can run an experiment with the train_full.csv (backbone doesn't change the result as far as I've tested)

**Comment by psinger** [comment]
Hi @fatihozturkh2o 

Did you try this on recent master?
I probably fixed the chat-issue very recently.

For HF there is an open issue:
https://github.com/h2oai/h2o-llmstudio/issues/30

**Comment by fatihozturkh2o** [comment]
Hi @psinger 

Nope, I fetched the repo yesterday and it seems my latest commit is at https://github.com/h2oai/h2o-llmstudio/commit/b9bba51fcdb70d4ef610569876f659af93e3b559

I'll pull the latest changes too and report back 👍

**Comment by fatihozturkh2o** [comment]
with the recent master:
- My old experiments' chat still fails with the same error
- If I run new experiment with "int8" selected, it works fine now 👍 
- HF push still fails with the following log:
```
2023-04-25 15:39:26,676 - ERROR: Unknown exception
Traceback (most recent call last):
  File "/home/fatih/h2o-llmstudio/./app_utils/handlers.py", line 301, in handle
    await experiment_push_to_huggingface_dialog(q)
  File "/home/fatih/h2o-llmstudio/./app_utils/sections/experiment.py", line 1544, in experiment_push_to_huggingface_dialog
    model.backbone = model.backbone.merge_and_unload()
  File "/home/fatih/h2o-llmstudio/venv/lib/python3.10/site-packages/peft/tuners/lora.py", line 308, in merge_and_unload
    raise ValueError("Cannot merge LORA layers when the model is loaded in 8-bit mode")
ValueError: Cannot merge LORA layers when the model is loaded in 8-bit mode
```

**Comment by psinger** [comment]
thanks, I will close this issue then as the HF push is know issue covered in https://github.com/h2oai/h2o-llmstudio/issues/30
