### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Chaosdrachin** [h2oai/h2o-llmstudio#578]
### 🐛 Bug
After Following the Install Instruction of [https://github.com/h2oai/h2o-llmstudio/issues/290](url)  and start of of LLM Studio:
i run in the following error (the Error Log)

Cuda Version : WSL Cuda : 11.5
Ubuntu Version: Ubuntu-22.04.3 LTS
WSL Version : wsl-2
h2o-llmstudio Version: 1.2.0 (the newest of main branch)

Error : 
`INFO:     127.0.0.1:57600 - "POST / HTTP/1.1" 200 OK
2024-01-23 11:15:44,411 - INFO: Initializing app ...
2024-01-23 11:15:44,421 - INFO: Initializing app ... done
2024-01-23 11:15:44,421 - INFO: Initializing client None
2024-01-23 11:15:44,425 - INFO: User name: anon
2024-01-23 11:15:44,425 - INFO: No user settings found. Using default settings.
2024-01-23 11:15:44,425 - INFO: Heap off
2024-01-23 11:15:44,558 - INFO: {'init_app'}
2024-01-23 11:15:44,562 - ERROR: Unknown exception
Traceback (most recent call last):
  File "/home/wyv3rn/Downloads/h2o-llmstudio/./llm_studio/app_utils/handlers.py", line 76, in handle
    await home(q)
  File "/home/wyv3rn/Downloads/h2o-llmstudio/./llm_studio/app_utils/sections/home.py", line 66, in home
    stats.append(ui.stat(label="Current GPU load", value=f"{get_gpu_usage():.1f}%"))
  File "/home/wyv3rn/Downloads/h2o-llmstudio/./llm_studio/app_utils/utils.py", line 1951, in get_gpu_usage
    usage /= len(all_gpus)
ZeroDivisionError: float division by zero
2024-01-23 11:15:44,563 - INFO: {'init_app'}
`
### To Reproduce
Follow the Install Instruction [https://github.com/h2oai/h2o-llmstudio/issues/290](url) and install cuda 11.5 instead of 12.3
Go to [http://localhost:10101/](url) to the UI and wait for the downloads of the datasets.
then take a look onto the Console and you will see the error

### LLM Studio version

Commit Version : dff97918d822567e56217fd96f753b1713d848a5

**Comment by pascal-pfeiffer** [comment]
Thank you for reporting. 
This error surfaces when LLM Studio is not able to detect any GPU on your system. Can you please run `nvidia-smi` in your WSL console to ensure that drivers are correctly installed.

**Comment by Chaosdrachin** [comment]
Nvidia-Smi said i have cuda and he shows my GPU
![Uploading 1.PNG…]()

**Comment by Chaosdrachin** [comment]
no problem :3

**Comment by pascal-pfeiffer** [comment]
https://github.com/h2oai/h2o-llmstudio/blob/dff97918d822567e56217fd96f753b1713d848a5/llm_studio/app_utils/utils.py#L1951

this could be modified to 
```python
if len(all_gpus) > 0:
    usage /= len(all_gpus)
```

Very interesting that `nvidia-smi` is working for you, as the [GPUtil](https://github.com/anderskm/gputil) package that we use for the GPU stats claims to grab the stats from the `nvidia-smi` output. 
>Requirements
>NVIDIA GPU with latest NVIDIA driver installed. GPUtil uses the program nvidia-smi to get the GPU status of all available NVIDIA GPUs. nvidia-smi should be installed automatically, when you install your NVIDIA driver.
