### ISSUE TITLE
[BUG] PermissionError: [Errno 13] Permission denied: '/workspace/data/user'

### ISSUE THREAD

**Issue by micsthepick** [h2oai/h2o-llmstudio#590]
### 🐛 Bug

2024-01-29 19:19:07,769 - ERROR: Unhandled exception
Traceback (most recent call last):
  File "/home/llmstudio/.local/share/virtualenvs/workspace-dqq3IVyd/lib/python3.10/site-packages/h2o_wave/server.py", line 374, in _process
    await self._handle(q)
  File "/workspace/./app.py", line 37, in serve
    await initialize_client(q)
  File "/workspace/./llm_studio/app_utils/initializers.py", line 124, in initialize_client
    os.makedirs(get_data_dir(q), exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/workspace/data/user'

### To Reproduce

Pulled the repository to latest main (8cf32e4528aca1d80a7517e87edd43b58d432e85), installed prerequisites to build dockerfile, built the docker image and ran as follows:

```
docker run --runtime=nvidia --shm-size=16g --init --rm -p10101:10101 -v `pwd`/data:/workspace/data -v `pwd`/output:/workspace/output -v /mldisk/.cache:/home/llmstudio/.cache h2o-llmstudio
```

### LLM Studio version
8cf32e4528aca1d80a7517e87edd43b58d432e85

**Comment by micsthepick** [comment]
issue resolved by changing owner back to user from root.

**Comment by micsthepick** [comment]
... Or so I thought, it still reports the same error.
