### ISSUE TITLE
[BUG] Recent regression causing an error when loading tokenizer for Deepseek models

### ISSUE THREAD

**Issue by tmostak** [h2oai/h2o-llmstudio#623]
### 🐛 Bug

I've been using LLM Studio to train with Deepseek-ai models for some time (i.e. https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base), but when I recently pulled master I saw that an error is now generated when loading the tokenizer for the model. as per the below.

This is occurring on commit 8232130f6dab99cfd74a4abcf0e9a00527246f5a, i.e. main, but when I rolled back to 1a997208b51b524303d92e2e82943cc2c9a8a8b3 (Fix IPO Loss), it works fine.

Let me know if I can provide any other info that might be helpful, but it seems easy to repro.

```
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
2024-03-01 21:54:06,826 - ERROR: Exception occurred during H2O LLM Studio run:
Traceback (most recent call last):
  File "/home/paperspace/h2o-llmstudio/llm_studio/src/datasets/text_utils.py", line 46, in get_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(cfg.llm_backbone, **kwargs)
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 825, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2048, in from_pretrained
    return cls._from_pretrained(
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2287, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama_fast.py", line 133, in __init__
    super().__init__(
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 117, in __init__
    slow_tokenizer = self.slow_tokenizer_class(*args, **kwargs)
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 182, in __init__
    self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 209, in get_spm_processor
    tokenizer.Load(self.vocab_file)
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paperspace/h2o-llmstudio/train_wave.py", line 106, in <module>
    run(cfg=cfg)
  File "/home/paperspace/h2o-llmstudio/train.py", line 520, in run
    train_dataset = get_train_dataset(train_df=train_df, cfg=cfg)
  File "/home/paperspace/h2o-llmstudio/llm_studio/src/utils/data_utils.py", line 387, in get_train_dataset
    train_dataset = cfg.dataset.dataset_class(df=train_df, cfg=cfg, mode="train")
  File "/home/paperspace/h2o-llmstudio/llm_studio/src/datasets/text_causal_language_modeling_ds.py", line 31, in __init__
    self.tokenizer = get_tokenizer(self.cfg)
  File "/home/paperspace/h2o-llmstudio/llm_studio/src/datasets/text_utils.py", line 51, in get_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(cfg.llm_backbone, **kwargs)
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 825, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2048, in from_pretrained
    return cls._from_pretrained(
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2287, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama_fast.py", line 133, in __init__
    super().__init__(
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 117, in __init__
    slow_tokenizer = self.slow_tokenizer_class(*args, **kwargs)
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 182, in __init__
    self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 209, in get_spm_processor
    tokenizer.Load(self.vocab_file)
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/paperspace/miniconda3/envs/h2o_llm/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
TypeError: not a string
```

**Comment by maxjeblick** [comment]
Thanks for reporting, this is probably caused by a recent transformers update to v4.38.1.
If possible, could you manually upgrade to https://github.com/huggingface/transformers/releases/tag/v4.38.2? We will upgrade to this version very soon.

**Comment by maxjeblick** [comment]
Seems to be an issue with transformers library/model:

```
import transformers
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "deepseek-ai/deepseek-coder-6.7b-base",
    add_prefix_space=False,
    use_fast=True,
)
```
Tokenizer init fails if `add_prefix_space` is set as an argument in `from_pretrained` classmethod (regardless whether it is True/False, also slow/fast doesn't make a difference).
