### ISSUE TITLE
[BUG] Error when pushing model to HuggingFace

### ISSUE THREAD

**Issue by jeffwang0516** [h2oai/h2o-llmstudio#635]
### 🐛 Bug
When trying to push finetuned model to HF OR download model,  `KeyError` occurred.
```
2024-03-12 15:45:24,520 - INFO: Loaded h2oai/h2ogpt-4096-llama2-7b.
2024-03-12 15:45:24,522 - INFO: Lora module names: ['q_proj', 'k_proj', 'v_proj', 'o_proj', 'gate_proj', 'up_proj', 'down_proj']
trainable params: 9,994,240 || all params: 6,748,409,856 || trainable%: 0.14809770321098886
2024-03-12 15:45:27,392 - ERROR: Unknown exception
Traceback (most recent call last):
  File "/home/jeff/h2o-llmstudio/./llm_studio/app_utils/handlers.py", line 337, in handle
    await experiment_push_to_huggingface_dialog(q)
  File "/home/jeff/h2o-llmstudio/./llm_studio/app_utils/sections/experiment.py", line 1808, in experiment_push_to_huggingface_dialog
    publish_model_to_hugging_face(
  File "/home/jeff/h2o-llmstudio/./llm_studio/app_utils/hugging_face_utils.py", line 108, in publish_model_to_hugging_face
    cfg, model, tokenizer = load_cfg_model_tokenizer(
  File "/home/jeff/h2o-llmstudio/./llm_studio/app_utils/sections/chat.py", line 201, in load_cfg_model_tokenizer
    load_checkpoint(cfg, model, strict=False)
  File "/home/jeff/h2o-llmstudio/./llm_studio/src/utils/modeling_utils.py", line 237, in load_checkpoint
    model = load_model_weights(model, model_weights, strict, cfg)
  File "/home/jeff/h2o-llmstudio/./llm_studio/src/utils/modeling_utils.py", line 153, in load_model_weights
    model_weights = {
  File "/home/jeff/h2o-llmstudio/./llm_studio/src/utils/modeling_utils.py", line 160, in <dictcomp>
    else model_state_dict[k]
KeyError: 'backbone.base_model.model.model.layers.0.self_attn.q_proj.base_layer.weight.quant_state.bitsandbytes__nf4'
```
### To Reproduce

- Run experiment with 
  - backbone_dtype: int4
  - lora enabled

### LLM Studio version
```
$ git rev-parse HEAD
80a75cd628f69ad7ae4f0ae850833ba813959041
```

**Comment by psinger** [comment]
Thanks @jeffwang0516 - I opened a PR to fix the issue.
