### ISSUE TITLE
[BUG] Deepseek tokenizer error on master

### ISSUE THREAD

**Issue by tmostak** [h2oai/h2o-llmstudio#743]
### 🐛 Bug

When attempting to train the [Deepseek 33b Base model](https://huggingface.co/deepseek-ai/deepseek-coder-33b-base), which I've done many times in the past, I'm getting the error below. Attempting to change the `Tokenizer Kwargs` in various ways still led to the same error.

```
TypeError: not a string
You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
2024-06-04 19:16:48,142 - ERROR: Exception occurred during H2O LLM Studio run:
Traceback (most recent call last):
  File "/home/ubuntu/h2o_llm_2024_05_04/train_wave.py", line 106, in <module>
    run(cfg=cfg)
  File "/home/ubuntu/h2o_llm_2024_05_04/train.py", line 535, in run
    train_dataset = get_train_dataset(train_df=train_df, cfg=cfg)
  File "/home/ubuntu/h2o_llm_2024_05_04/llm_studio/src/utils/data_utils.py", line 393, in get_train_dataset
    train_dataset = cfg.dataset.dataset_class(df=train_df, cfg=cfg, mode="train")
  File "/home/ubuntu/h2o_llm_2024_05_04/llm_studio/src/datasets/text_causal_language_modeling_ds.py", line 30, in __init__
    self.tokenizer = get_tokenizer(self.cfg)
  File "/home/ubuntu/h2o_llm_2024_05_04/llm_studio/src/datasets/text_utils.py", line 49, in get_tokenizer
    tokenizer_class = AutoTokenizer.from_pretrained(
  File "/home/ubuntu/miniconda3/envs/h2o_llm_2024_05_28/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 862, in
 from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/ubuntu/miniconda3/envs/h2o_llm_2024_05_28/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2089, in from_pretrained
    return cls._from_pretrained(
  File "/home/ubuntu/miniconda3/envs/h2o_llm_2024_05_28/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2311, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/home/ubuntu/miniconda3/envs/h2o_llm_2024_05_28/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama_fast.py", line 124, in __init__
    super().__init__(
  File "/home/ubuntu/miniconda3/envs/h2o_llm_2024_05_28/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py", line 117, in __init__
    slow_tokenizer = self.slow_tokenizer_class(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/h2o_llm_2024_05_28/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 169, in __init__
    self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
  File "/home/ubuntu/miniconda3/envs/h2o_llm_2024_05_28/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 196, in get_spm_processor
    tokenizer.Load(self.vocab_file)
  File "/home/ubuntu/miniconda3/envs/h2o_llm_2024_05_28/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/ubuntu/miniconda3/envs/h2o_llm_2024_05_28/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
```

### To Reproduce

Do any fine-tune of a Deepseek coder model (I assume it doesn't have to be 33b, could be their 6.7b model)

### LLM Studio version
Main (4897f4cce174899f21d3b281e823b00de2a04329)

**Comment by psinger** [comment]
Thanks for reporting, will take a look.

Did you also upgrade the packages (transformer) accordingly?

**Comment by tmostak** [comment]
Hi @psinger,

Transformers is on 4.40.2, per the `requirements.txt` (and everything else should match that as well).

And when I remove `add_prefix_space` from the kwargs string, I get 

```
  File "/home/ubuntu/h2o_llm_2024_05_04/llm_studio/src/datasets/text_utils.py", line 66, in get_tokenizer
    kwargs.pop("add_prefix_space")
KeyError: 'add_prefix_space'
```

as it is popping the key from the dictionary but its not there now.
